apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rpclient-vs
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - route:
        - destination:
            host: rpclient-service.default.svc.cluster.local
            port:
              number: 3000


